# This is a basic workflow to help you get started with Actions

name: React CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x,16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --no-optional
      working-directory: ./frontend
    - run: npm run build --if-present
      working-directory: ./frontend
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "a982f082-c32f-4ceb-8279-c1831741ff71"
          heroku_app_name: "dream-team-crm"
          heroku_email: "kowji@student.unimelb.edu.au"
          buildpack: "https://github.com/mars/create-react-app-buildpack.git"
          appdir: "frontend"
