# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Build React
      run: npm run build
      
    - name: Build 
      run: npm run build
      working-directory: ./backend
      
    - name: Git deploy to Heroku
      uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
      with:
        api_key: "a982f082-c32f-4ceb-8279-c1831741ff71"
        email: "kowji@student.unimelb.edu.au"
        app_name: "dream-team-crm"
        branch: "main"
        subfolder: "build"
      

